### ISSUE TITLE
Unable to replace or delete & re-add X7 files into client

### ISSUE THREAD

**Issue by shanzenos** [FreeDenny9700/S4_NetSphere_ResourceTool_Season1#1]
No matter which way I do it, attempting to delete & re-add or use replace on iteminfo.x7 for example, it will cause the client to no longer load, but if I delete iteminfo.x7 after I've tried this it loads up initially (only to crash later of course, when it tries to load into the game server and realizes the file is missing). There any known reason for this? Does replacing existing files not work?

**Comment by FreeDenny9700** [comment]
Unfortunately, the error is due to the library of Blub. I have already asked for help to him because I 'm not able to fix it. I'm trying

**Comment by shanzenos** [comment]
Ah, well he did update his LZO libraries a few days ago, but I just got done trying those and same issue it would seem. Is it the main "blublib" library that's causing it?

**Comment by FreeDenny9700** [comment]
No, the library what manages the encrypt and decrypt of x7 files does not work correctly

**Comment by shanzenos** [comment]
the files in question wouldn't happen to be these would they? https://github.com/wtfblub/NetspherePirates/commit/22f54e3513de1439fb9ef6b3fa3e211c1750091c

**Comment by FreeDenny9700** [comment]
which tool you are using ?

**Comment by shanzenos** [comment]
The one the source compiles into. You're right, I just never noticed it was only happening to the x7 files since they're the ones I was trying to import my edits to. So it's an issue with blub's libraries? hopefully he updates them again so I can finally continue my work.

**Comment by BioAleks** [comment]
Fody.WeavingTask error when compile. I download your updated source.

**Comment by FreeDenny9700** [comment]
Download my ResTool Source without References.

[Source without reference](https://github.com/FreeDenny9700/S4_NetSphere_ResourceTool_Season1/tree/master/NetspherePirates_ResTool%20(No%20References))

**Comment by FreeDenny9700** [comment]
PS: Now i upload on GitHub my new tool for decompile .LUA files.

**Comment by BioAleks** [comment]
> Download my ResTool Source without References.
I download it and say - "Save now working".

Add dialog "add files folder/file - complete" and dialog with "no complete". Understand or add picture?

**Comment by FreeDenny9700** [comment]
Please you Can test my last version of Tool? Go to releases and download version 1.1.0.0

**Comment by BioAleks** [comment]
One file? Error.

**Comment by FreeDenny9700** [comment]
Ok, thanks for report, Windows is a shit system. Now i delete this shitty release. Explain me your preview idea for ResTool

**Comment by BioAleks** [comment]
`F5 for update`
I no see new added files by me in .s4hd. If i reload tool - I see it. So you can add "autoupdate" or "update button" that can be used like button or by clicking F5. 

**Second is...**
If one/two/etc files no added in .s4hd - open dialog box with files, that no be added in .s4hd
If all files added OK - open dialog that say "Complete".

**Comment by FreeDenny9700** [comment]
Yeah it is an excellent idea, today i make this new functions

**Comment by BioAleks** [comment]
And lol. Fuck this error. After using tool now "save error" appear.

**Comment by FreeDenny9700** [comment]
You Can send me video of this error, it is strange.. with my use, i not see error with save function

**Comment by BioAleks** [comment]
When I load res and click "Save" button - error. If all be okay - I can compile tool, but I can't.
What problem with that Fody?
I add error message.
[buglog.txt](https://github.com/FreeDenny9700/S4_NetSphere_ResourceTool_Season1/files/373753/buglog.txt)

**Comment by FreeDenny9700** [comment]
Null reference... I must view code and fix this

**Comment by BioAleks** [comment]
"Object reference does not point to an instance of an object".

**Comment by FreeDenny9700** [comment]
I found perhaps the error

**Comment by BioAleks** [comment]
I test if need.

**Comment by FreeDenny9700** [comment]
Now you can test my latest version of ResTool. Thanks for your work bro

**Comment by BioAleks** [comment]
Don't see now any error, but time will tell if be. 
If be - i post.

**Comment by FreeDenny9700** [comment]
Ok, thanks so much

**Comment by BioAleks** [comment]
So, here only one problem left: x7 files.
And you have my idea for new update.

**Comment by FreeDenny9700** [comment]
Yes, now i have problem to compile LUA file because i can't add into client LUA decompiled

**Comment by FreeDenny9700** [comment]
I have released now new update of ResTool with your features. Test it, good work

**Comment by BioAleks** [comment]
How about add message "save complete"?

**Comment by FreeDenny9700** [comment]
Uhm today i add status label

**Comment by BioAleks** [comment]
Because who know complete it or no...

**Comment by FreeDenny9700** [comment]
Eh??

**Comment by BioAleks** [comment]
I'm about "save" message. Who know launcher complete save or no if i no go to folder for see it? Message help.

**Comment by FreeDenny9700** [comment]
ok, anyway you can use my source to add some function to tool

**Comment by BioAleks** [comment]
I found bug.

What I do:
1. I use "replace" function for replace file;
2. After replace function I use "add" function and see this bug:
I can add ONLY .xml files (if i use replace for .xml files), dds files (if i use replace for .dds files) and etc.

Bug:
I can't use another format files for add function if i use replace files function. 
Can add only format, that i use in replace function.

**Comment by FreeDenny9700** [comment]
Now i fix this, wait :)

**Comment by FreeDenny9700** [comment]
I have been fixed filter system on Dialog Box. Thanks for your Report.
For some error, please open new Issues.
