### ISSUE TITLE
Kafèèèèèèèèèè!!?!??!?!?!??!!

### ISSUE THREAD

**Issue by RuggeroDeCeglie** [FreeDenny9700/S4_NetSphere_ResourceTool_Season1#5]
.....................

**Comment by WAZAAAAA0** [comment]
per la madonna ma che cazzo dici

**Comment by FreeDenny9700** [comment]
Ma lo sai che le segnalazioni su Github servono per informare il programmatore di errori, avvertimenti ecc? Non intasare il mio profilo con queste stupidaggini
