### ISSUE TITLE
SharpLzo.miniLzo Exception

### ISSUE THREAD

**Issue by redapro** [FreeDenny9700/S4_NetSphere_ResourceTool_Season1#6]
When I do any function ( Add-Replace-Extract-Etc....)
This message pops up and breaks the function and the function isn't working after that..
Pic is in Attachments!
![untitled](https://cloud.githubusercontent.com/assets/21015911/18051787/f977d13e-6df6-11e6-844a-2a3a8a1a003e.png)

**Comment by FreeDenny9700** [comment]
Download Pre-Build package from Release Page, extract all and Run as Administrator .exe file.
